workflow = """\
name: Run Ansible Playbook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook hello_playbook.yml -i localhost,
"""

!mkdir -p .github/workflows
with open(".github/workflows/run-playbook.yml", "w") as f:
    f.write(workflow)
